# Generated by Django 2.2.25 on 2022-04-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0002_bonhomme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonHomme',
        ),
    ]
