# Generated by Django 2.2.25 on 2022-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0003_delete_bonhomme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='num',
            field=models.IntegerField(),
        ),
    ]
